# Site settings
title: 'Jasmine "lnishan" Chen'
description: 'An eternal dream pursuer'
url: 'https://lnishan.github.io'
baseurl: ''
timezone: 'Asia/Taipei'
cv: 'https://lnishan.github.io/Curriculum-Vitae/'
google_analytics: 'UA-90684411-1'
excerpt_separator: '<!--more-->'

author:
  name: 'Jasmine Chen'
  email: jasmine.chen.cs@gmail.com
  twitter_username: lnishantw
  facebook_username: lnishantw
  github_username: lnishan
  linkedin_username: lnishantw

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
